package com.company.game;


import com.company.core.Position;
import com.company.figures.figure_impls.Bishop;

import static com.company.core.BoardLetters.H;

public class Game {

    public static final Board board = new Board();
    private static final MoveReader moveReader = new MoveReader(board);

    public static void start() {
        board.resetBoard();
//        moveReader.requestMove();
        moveReader.makeMove("e4");
        moveReader.makeMove("Nc6");
        moveReader.makeMove("d4");
        moveReader.makeMove("d5");
        moveReader.makeMove("e5");
        moveReader.makeMove("e6");
        moveReader.makeMove("Nf3");
        moveReader.makeMove("a6");
        moveReader.makeMove("Bd3");
        moveReader.makeMove("Bb4+");
        moveReader.makeMove("c3");
        moveReader.makeMove("Be7");
        moveReader.makeMove("Be3");
        moveReader.makeMove("b5");
        moveReader.makeMove("b4");
        moveReader.makeMove("h6");
        moveReader.makeMove("Nbd2");
        moveReader.makeMove("Bb7");
        moveReader.makeMove("a4");
        moveReader.makeMove("bxa4");
        moveReader.makeMove("Rxa4");
        moveReader.makeMove("f5");
        moveReader.makeMove("Nb3");
        moveReader.makeMove("Qd7");
        moveReader.makeMove("Nfd2");
        moveReader.makeMove("Bg5");
        moveReader.makeMove("Nc5");
        moveReader.makeMove("Qc8");
        moveReader.makeMove("O-O");
        moveReader.makeMove("Bxe3");
        moveReader.makeMove("fxe3");
        moveReader.makeMove("Nge7");
        moveReader.makeMove("Qa1");
        moveReader.makeMove("O-O");
        moveReader.makeMove("Nxa6");
        moveReader.makeMove("Ng6");
        moveReader.makeMove("Nc5");
        moveReader.makeMove("Rxa4");
        moveReader.makeMove("Qxa4");
        moveReader.makeMove("Qa8");
        moveReader.makeMove("Bc2");
        moveReader.makeMove("f4");
        moveReader.makeMove("Bxg6");
        moveReader.makeMove("fxe3");
        moveReader.makeMove("Qxa8");
        moveReader.makeMove("Bxa8");
        moveReader.makeMove("Ndb3");
        moveReader.makeMove("e2");
        moveReader.makeMove("Rxf8+");
        moveReader.makeMove("Kxf8");
        moveReader.makeMove("Kf2");
        moveReader.makeMove("e1=Q+");
        moveReader.makeMove("Kxe1");
        moveReader.makeMove("Ke7");
        moveReader.makeMove("Na6");
        moveReader.makeMove("Kd8");
        moveReader.makeMove("Nbc5");
        moveReader.makeMove("Ne7");
        moveReader.makeMove("Bf7");
        moveReader.makeMove("c6");
        moveReader.makeMove("Nxe6+");
        moveReader.makeMove("Kc8");
        moveReader.makeMove("Nxg7");
        moveReader.makeMove("Kb7");
        moveReader.makeMove("Nc5+");
        moveReader.makeMove("Kb6");
        moveReader.makeMove("g4");
        moveReader.makeMove("Kb5");
        moveReader.makeMove("Nf5");
        moveReader.makeMove("Nc8");
        moveReader.makeMove("e6");
        moveReader.makeMove("Kc4");
        moveReader.makeMove("e7");
        moveReader.makeMove("Nxe7");
        moveReader.makeMove("Nxe7");
        moveReader.makeMove("Kxc3");
        moveReader.makeMove("Nxd5+");
        moveReader.makeMove("cxd5");
        moveReader.makeMove("Bxd5");
        moveReader.makeMove("Bxd5");
        moveReader.makeMove("b5");
        moveReader.makeMove("Kxd4");
        moveReader.makeMove("Na4");
        moveReader.makeMove("Ke5");
        moveReader.makeMove("h4");
        moveReader.makeMove("Kf4");
        moveReader.makeMove("g5");
        moveReader.makeMove("h5");
        moveReader.makeMove("Kd2");
        moveReader.makeMove("Kg4");
        moveReader.makeMove("Ke3");
        moveReader.makeMove("Kxh4");
        moveReader.makeMove("Kf4");
        moveReader.makeMove("Bb7");
        moveReader.makeMove("g6");
        moveReader.makeMove("Kh3");
        moveReader.makeMove("Kg5");
        moveReader.makeMove("h4");
        moveReader.makeMove("g7");
        moveReader.makeMove("Bd5");
        moveReader.makeMove("b6");
        moveReader.makeMove("Kg3");
        moveReader.makeMove("b7");
        moveReader.makeMove("h3");
        moveReader.makeMove("b8=Q+");
        moveReader.makeMove("Kf2");
        moveReader.makeMove("Qf4+");
        moveReader.makeMove("Bf3");
        moveReader.makeMove("Kh4");
        moveReader.makeMove("Kg2");
        moveReader.makeMove("Qg3+");
        moveReader.makeMove("Kf1");
        moveReader.makeMove("Qxf3+");
        moveReader.makeMove("Ke1");
        moveReader.makeMove("Qxh3");
        moveReader.makeMove("Kd1");
        moveReader.makeMove("g8=R");
        moveReader.makeMove("Ke1");
        moveReader.makeMove("Qh2");
        moveReader.makeMove("Kf1");
        moveReader.requestMove();
    }
}
